In [25]:
import deepcut
import numpy as np
from tensorflow.keras.preprocessing import sequence
from tensorflow import keras
from pythainlp import word_vector

In [50]:
with open('corpus.txt') as f:
    xtrain = []
    ytrain = []
    for line in f.readlines():
        temp = line.split()
        if len(temp) == 2:
            xtrain.append(temp[0])
            ytrain.append(temp[-1])
        elif len(temp) > 2:
            join = " ".join(temp[0:-1])
            xtrain.append(join)
            ytrain.append(temp[-1])
#         print(line)
print(xtrain)
print(len(xtrain))

['ส่วนบริเวณยอดดอยและยอดภูมีอากาศหนาว', 'ส่วนบริเวณยอดดอยและยอดภูมีอากาสหนว', 'ได้อ่อนกำลังลงเป็นหย่อมความกดอากาศต่ำกำลังแรงบริเวณใกล้ชายฝั่งประเทศเวียดนามตอนกลางแล้ว', 'ได้อ่อนกำลังลงเป็ยหย่อมความกดอากาสต่ำกำลังแรงบริเวณใกล้ชายฝั่งประเทศเวียตนามตอนกลงแล้ว', 'บริเวณภาคตะวันออกเฉียงเหนือตอนล่าง และภาคตะวันออก มีฝนเล็กน้อยถึงปานกลางกับมีลมแรง', 'บริฌวณถาคตะวันออกเฉียงเหนีอตอนล่าง และถาคตะวันออก มีฝนเล็กน้อยถึงปานกลษงกับมีลมแรง', 'บริเวณความกดอากาศสูงกำลังปานกลางหรือมวลอากาศเย็นจากประเทศจีนแผ่ปกคลุมประเทศไทยตอนบน', 'บริเวณคาวมกดอากาสสูงกำลังปานกลางหรือมวลอากาศเย็ฯจากประเทสจืนแผ่ปกคลุมประเทศไทยตอนบน', 'ได้เคลื่อนขึ้นฝั่งบริเวณดังกล่าวและคาดว่าจะอ่อนกำลังลงอีกเป็นหย่อมความกดอากาศต่ำในระยะต่อไป', 'ได้เคลิ่อนขึ้นฝั่งบริเวณดังกล่วและคาดว่าจะอ่อนกำลังลงอีกเป็ฯหย่อมความกดอากาศต่ำในระยะต่อไป', 'ทำให้บริเวณดังกล่าวมีอากาศเย็น โดยมีฝนบางแห่ง', 'ทำให้บริเวญดังกล่วมีอากาศเย็ฯโดยมีฝนบางแห่ง', 'ส่วนบริเวณยอดดอยและยอดภูมีอากาศหนาว สำหรับมรสุมตะวันออกเฉียงเหนือพัดปกคลุมอ่าวไทยและภาคใต้', 'ส่วนบริเวณยอดดอ

In [51]:
print(ytrain)
print(len(ytrain))

['ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด', 'ถูก', 'ผิด']
50


In [52]:
# x_train = ['วันนี้วันจันทร์','วันนี้วันศุกร์','วันนี้วันเสาร์','วันนีวันจันทนะ','วันนีวันศุกนะ','วันนีวันศุร์นะ','วันนี้วันศุกร์นะ','วันนี้วันจันทร์นะ',]
# y_train = ['ถูก','ถูก','ถูก','ผิด','ผิด','ผิด','ถูก','ถูก',]
# x_test = ['วันนี้วันพุธ','วันนี้วันอังคาร','วันนี้วันอังคาน','วันนี้วัลพุธ']

In [53]:
# corpus = ['วันนี้วันจันทร์','วันนี้วันศุกร์','วันนี้วันเสาร์','วันนีวันจันทนะ','วันนีวันศุกนะ',
#           'วันนีวันศุร์นะ','วันนี้วันศุกร์นะ','วันนี้วันจันทร์นะ','วันนี้วันพุธ','วันนี้วันอังคาร','วันนี้วันอังคาน','วันนี้วัลพุธ']

In [54]:
test = deepcut.tokenize('วันนี้วันศุร์นะ')
print(test)

['วัน', 'นี้', 'วัน', 'ศุร์นะ']


In [55]:
def word_tokenize(corpus):
    x = 0
    words = []
    for i in corpus:
        list_word = deepcut.tokenize(i,custom_dict='custom_dict.txt') #ตัดคำ
        words.append(list_word)
        x += 1
    return words
# corpus=word_tokenize(corpus)
# x_test = word_tokenize(x_test)
words = word_tokenize(xtrain)
# print(words)
# print(len(words))

In [56]:
def add_1list(word_list):
    list_ = []
    vocab = []
    for l in word_list:
        list_.extend(l)
#     print(list_)
    word_v = set(list_)
    for list_d in word_v:
        vocab.append(list_d)
    vocab = [' '] + vocab
    return vocab

vocab = add_1list(words)
print(vocab)
print(len(vocab))

[' ', 'ภากใต้', 'ใน', 'หลย', 'ไป', 'เหนีอพัด', 'เนื่อง', 'ลง', 'นี้', 'เย็น', 'ตอนกลง', 'ยอด', 'ไว้', 'จืน', 'ด้าน', 'ตอยบน', 'อีก', 'พื้นที่', 'พัด', 'ดูแล', 'สุขภาพ', 'ลม', 'ตาม', 'ช่วง', 'อันดามัน', 'ผล', 'บริเวณ', 'ฝั่ง', 'เคลื่อน', 'จะ', 'ควม', 'ชัน', 'สะภาพ', 'ประเทศฟิลิปปินส์', 'ความ', 'ประเทศฟิลิปปิน', 'สุขภาบ', 'นื้', 'หนัด', 'จาก', 'แผ่', 'ร่อง', 'ยอดภู', 'กว้าง', 'ระมัดระวัง', 'โดย', 'ใต้', 'เปลี่ยนแปลง', 'แล้ง', 'สู่', 'ภาค', 'ชาย', 'คาว', 'ตะวัน', 'ปณะ', 'กำลัง', 'ฝ', 'ปานกลาง', 'คาด', 'อษกาศ', 'ประเทศไทย', 'มี', 'เคลิ่อน', 'แห่', 'สำหรับ', 'ตด', 'ถึง', 'ลำดับ', 'อากาศ', 'เล็กน้อ', 'คาวม', 'ฝน', 'ล่าง', 'เย็ฯ', 'เป็ย', 'ว่า', 'เรีอ', 'ให้', 'ประเทศเวียตนาม', 'ต่อ', 'หลาย', 'กล่าว', 'ทำ', 'อากาส', 'ภาก', 'ม', 'เป็', 'เฉียง', 'หย่อม', 'ที่', 'พาด', 'หนัก', 'เทศ', 'เคลิ่อฯ', 'เวียกนาม', 'ของ', 'โซนร้อน', 'ฝนฟ้า', 'แรง', 'แห่ว', 'ทะเล', 'ปกคลุม', 'ถาค', 'เปลี่ยนแปรง', 'และ', 'จีนใต้', 'กับ', 'สูง', 'ยังคง', 'บริฌวณ', 'ประเทส', 'ประเทศเวียดนาม', 'ปกครุม', 'กด', 'ตก', 'มาก', 'มร

In [9]:
# words1 = []
# x = 0
# y = 0
# for text in range(len(words)):
#     for word in range(len(words[y])):
#         words1.append(words[y][x])
#         x += 1
#     y += 1
#     x = 0
# print(words1)
# words1 = set(words1)
# print(words1)
# # vocab = []
# # for list_d in words1:
# #     vocab.append(list_d)
# # vocab = [' '] + vocab
# # print(vocab)
# # print(len(vocab))

In [27]:
w2v = word_vector.get_model()

In [43]:
vecter = []
vocab_ = []
index = 0
for word in w2v.index2word:
    vocab_.append(word)
    vecter.append(w2v[word])
#     thai2dict[word] = w2v[word]
#     print(word)

In [61]:
vocab_ = [''] + vocab_
vecter = np.vstack((np.random.rand(*vecter[0].shape), vecter))

In [60]:
print(vocab_[0])
print(len(vocab_))


51359


In [108]:
# print(vecter[0])

In [65]:
def sent2idx(x):
    xidx = []
    for w in x:
#         print(w)
        if w in vocab_:
            xidx.append(vocab_.index(w))
        else:
            xidx.append(0)
    return np.array(xidx)

In [66]:
sent2idx(words[1])

array([   99,   214,   750,  2923,     3,   750, 26024,     0,     0])

In [70]:
def word_seq(words):
    Xtrain_idx = []
    maxlen = 0
    for x in words:
        Xtrain_idx.append(sent2idx(x))
        if len(Xtrain_idx[-1]) > maxlen:
            maxlen = len(Xtrain_idx[-1])
#         print(len(Xtrain_idx[-1]))
    print(maxlen)
    return Xtrain_idx

In [71]:
# Xtest = word_seq(x_test)
# print(Xtest)
Xtrain = np.array(word_seq(words))
print(Xtrain)

30
[array([   99,   214,   750,  2923,     3,   750, 26024,  1163,  6525])
 array([   99,   214,   750,  2923,     3,   750, 26024,     0,     0])
 array([    7,  1329,   333,   111,     4, 16600,   101,  1859,  1163,
        1315,   333,  1026,   214,   678,   391,  1081,     0,   319,
         349,    63])
 array([    7,  1329,   333,   111, 38102, 16600,   101,  1859,     0,
        1315,   333,  1026,   214,   678,   391,  1081,     0,   319,
           0,    63])
 array([ 214,  277, 3607,   83, 8185,  455,  319, 1851,    0,    3,  277,
       3607,   83,    0,    6, 3223, 1451,   73, 4939,   15,    6,  812,
       1026])
 array([   0,    0, 3607,   83, 8185,    0,  319, 1851,    0,    3,    0,
         83,    0,    6, 3223, 1451,   73,    0,   15,    6,  812, 1026])
 array([ 214,  101, 1859, 1163,  259,  333, 4939,   32, 2068, 1163, 1931,
         19, 1398, 4331, 3241,  209,  319,  136])
 array([ 214,    0, 1859,    0,  259,  333, 4939,   32, 2068, 1163,    0,
         19,    0,  

In [72]:
Xtrain = sequence.pad_sequences(np.array(Xtrain),padding='pre')
print(Xtrain)

[[    0     0     0 ... 26024  1163  6525]
 [    0     0     0 ... 26024     0     0]
 [    0     0     0 ...   319   349    63]
 ...
 [    0     0     0 ...     6   812  1026]
 [    0     0     0 ...     6     0 17772]
 [    0     0     0 ...     6     0 17772]]


In [73]:
Xtrain.shape

(50, 30)

In [74]:
intput_lenght = len(Xtrain[0])
print(intput_lenght)
vocab_size = len(vocab)+1

30


In [75]:
# Xtest = sequence.pad_sequences(np.array(Xtest),maxlen=intput_lenght,padding='pre')
# print(Xtest)

In [76]:
y_train = []
for i in ytrain:
    if i == 'ถูก':
        y_train.append(1)
    else:
        y_train.append(0)
print(y_train)

[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]


In [95]:
model = keras.Sequential()
model.add(keras.layers.Embedding(vecter.shape[0], vecter.shape[1], name='embed'))
model.add(keras.layers.Bidirectional(keras.layers.LSTM(128, return_sequences=True)))
model.add(keras.layers.Bidirectional(keras.layers.LSTM(64)))
model.add(keras.layers.Dense(128, activation=keras.activations.relu))
model.add(keras.layers.Dense(2))

In [96]:
model.compile(loss=keras.losses.sparse_categorical_crossentropy, optimizer=keras.optimizers.Adam(learning_rate=1e-4))

In [97]:
model.get_layer('embed').set_weights([vecter])
model.get_layer('embed').trainable = False

In [98]:
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embed (Embedding)            (None, None, 300)         15407700  
_________________________________________________________________
bidirectional_4 (Bidirection (None, None, 256)         439296    
_________________________________________________________________
bidirectional_5 (Bidirection (None, 128)               164352    
_________________________________________________________________
dense_18 (Dense)             (None, 128)               16512     
_________________________________________________________________
dense_19 (Dense)             (None, 2)                 258       
Total params: 16,028,118
Trainable params: 620,418
Non-trainable params: 15,407,700
_________________________________________________________________
None


In [105]:
model.fit(Xtrain, np.array(y_train), epochs=50)

Epoch 1/50
2/2 [==============================] - 0s 54ms/step - loss: 0.6931
Epoch 2/50
2/2 [==============================] - 0s 59ms/step - loss: 0.6931
Epoch 3/50
2/2 [==============================] - 0s 54ms/step - loss: 0.6931
Epoch 4/50
2/2 [==============================] - 0s 58ms/step - loss: 0.6931
Epoch 5/50
2/2 [==============================] - 0s 54ms/step - loss: 0.6931
Epoch 6/50
2/2 [==============================] - 0s 56ms/step - loss: 0.6931
Epoch 7/50
2/2 [==============================] - 0s 57ms/step - loss: 0.6931
Epoch 8/50
2/2 [==============================] - 0s 55ms/step - loss: 0.6931
Epoch 9/50
2/2 [==============================] - 0s 54ms/step - loss: 0.6931
Epoch 10/50
2/2 [==============================] - 0s 59ms/step - loss: 0.6931
Epoch 11/50
2/2 [==============================] - 0s 57ms/step - loss: 0.6931
Epoch 12/50
2/2 [==============================] - 0s 52ms/step - loss: 0.6931
Epoch 13/50
2/2 [==============================] - 0s 56ms/st

In [106]:
score = model.evaluate(Xtrain,np.array(y_train),verbose=1)
print(score)

2/2 [==============================] - 0s 3ms/step - loss: 0.6931
0.6931471824645996


In [107]:
model.predict(Xtrain).argmax(axis=1)

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0], dtype=int64)

In [46]:
# model.predict(Xtest).argmax(axis=1)